services:
  - type: web
    name: ramirez-lima
    env: node
    plan: free
    repo: https://github.com/RamirezLima/devops_aplicacao_ci_cd
    branch: AppJavaScript
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ramirez-lima-postgre
          property: connectionString

databases:
  - name: ramirez-lima-postgre
    plan: free
    region: oregon