name: CI - Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit

    - name: Check Streamlit version
      run: streamlit --version

    - name: Run app script syntax check
      run: python ferramentas_professores.py --help || true

    - name: Run basic smoke test
      run: |
        # Testa se o script roda sem erro (não abre interface)
        python -c "import ferramentas_professores"
